import { fetchApi } from '@/lib/api';
interface Report { generatedAt: string; period: { from: string; to: string }; orderCount: number; pendingOrderCount: number; observedOrderTotal: number | null; sources: { id: string; name: string; source: string; lastSyncedAt: string | null; lastSyncState?: string; orderCount: number }[]; gaps: string[]; }
export default async function ObservationPage({ searchParams }: { searchParams: Promise<{ from?: string; to?: string }> }) {
  const params = await searchParams; const query = new URLSearchParams();
  if (params.from) query.set('from', params.from); if (params.to) query.set('to', params.to);
  const { data: report } = await fetchApi<Report>(`/observation/report?${query}`);
  const fmt = (s: string) => new Date(s).toLocaleString('pt-BR', { timeZone: 'UTC' });
  return <article className="mx-auto max-w-5xl space-y-8">
    <header className="border-b pb-6"><p className="text-xs uppercase tracking-widest text-emerald-700">Farmaecon · AI Office / Observação</p><h1 className="mt-3 text-4xl font-semibold tracking-tight">O que os dados permitem afirmar</h1><p className="mt-3 text-muted-foreground">Análise determinística. Nenhuma ação comercial é executada.</p></header>
    <form className="flex flex-wrap items-end gap-4"><label className="text-sm">Início (UTC)<input aria-label="Início do período" className="block rounded border p-2" type="datetime-local" name="from" defaultValue={report.period.from.slice(0,16)} required /></label><label className="text-sm">Fim (UTC)<input aria-label="Fim do período" className="block rounded border p-2" type="datetime-local" name="to" defaultValue={report.period.to.slice(0,16)} required /></label><button className="rounded bg-emerald-900 px-5 py-2 text-white">Atualizar relatório</button></form>
    <p className="text-sm text-muted-foreground">{fmt(report.period.from)} — {fmt(report.period.to)} UTC · Gerado em {fmt(report.generatedAt)} UTC</p>
    <div className="grid gap-4 sm:grid-cols-3">{[['Pedidos observados', report.orderCount], ['Pedidos pendentes', report.pendingOrderCount], ['Lucro líquido', 'Indisponível']].map(([label,value]) => <div className="rounded-xl border p-6" key={label}><p className="text-sm text-muted-foreground">{label}</p><p className="mt-3 text-3xl font-semibold">{value}</p></div>)}</div>
    <section><h2 className="mb-4 text-xl font-semibold">Origem e atualização</h2><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="border-b"><tr>{['Conta','Origem','Última sincronização (UTC)','Pedidos no período'].map(h => <th key={h} className="p-3">{h}</th>)}</tr></thead><tbody>{report.sources.map(s => <tr key={s.id} className="border-b"><td className="p-3">{s.name}</td><td className="p-3">{s.source === 'SIMULATED' ? 'SIMULAÇÃO LOCAL' : s.source}</td><td className="p-3">{s.lastSyncedAt ? fmt(s.lastSyncedAt) : 'Não realizada'}</td><td className="p-3">{s.orderCount}</td></tr>)}</tbody></table></div>{!report.sources.length && <p className="p-4">Nenhuma fonte disponível nesta empresa.</p>}</section>
    <section className="rounded-xl border border-amber-300 bg-amber-50 p-6 text-amber-950"><h2 className="text-xl font-semibold">Limites deste relatório</h2><ul className="mt-3 list-disc space-y-2 pl-5"><li>Valores de pedidos não comprovam receita liquidada.</li><li>Taxas, custos, frete, impostos e reembolsos não têm cobertura certificada. DRE e margem estão indisponíveis.</li><li>Paginação incompleta, datas ou valores inválidos interrompem a sincronização. A cobertura integral do período ainda precisa ser conferida com a fonte.</li>{report.sources.some(s => s.source === 'SIMULATED') && <li>Dados sintéticos para homologação. Não representam vendas reais.</li>}{report.sources.some(s => s.lastSyncState === 'FAILED') && <li>A última tentativa de sincronização falhou. Os dados anteriores podem estar desatualizados.</li>}{(!report.sources.length || report.sources.some(s => !s.lastSyncedAt)) && <li>Há fontes sem sincronização concluída.</li>}</ul></section>
    <footer className="text-sm text-muted-foreground">Próxima revisão humana: conferir pedidos pendentes e completar a conciliação financeira.</footer>
  </article>;
}
