version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: farmaecon-postgres
    restart: always
    environment:
      POSTGRES_USER: farmaecon
      POSTGRES_PASSWORD: secretpassword
      POSTGRES_DB: farmaecon_db
    ports:
      - '5432:5432'
    volumes:
      - farmaecon-pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: farmaecon-redis
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - farmaecon-redisdata:/data

volumes:
  farmaecon-pgdata:
  farmaecon-redisdata:
